### ISSUE TITLE
Script Only Adds First Record

### ISSUE THREAD

**Issue by TeleBrady** [ligouras/kuma-init#1]
Thanks for creating this script. I tried running it in my environment and it seems to only add the very first record in the .csv file. When I add console logging (shown below) and run the script it spits out every line in the file, but it's only adding the first entry to Uptime Kuma (no errors are shown in Uptime Kuma or otherwise) -
```
                    if (options.dryRun !== true) {
                        // add monitor
                        socket.emit('add', { ...monitor, type: 'http', name: row[0], url: row[1]});
                        console.log('Added monitor', { type: 'http', name: row[0], url: row[1]});
```

Any ideas?

**Comment by mahendratala** [comment]
I think you need to create bash script to iterate the function 

```
#!/bin/bash
while IFS=, read -r name url; do
 echo "$name,$url" | node client.js -s uptime.nectarwebsite.com -u support@nectar.id -p 5R*FEEy0l280G%@#
done < monitors.csv
```

that is how i managed to do the real batch/bulk add monitor
